strategy_name: EtfFiStrategy

market_monitor:

  #strategy_name: MarketMonitorDummy

  number_of_days: 14
  price_snipping_time_string: "17:15:00"  # Ricorda di mettere l'ora come stringa in YAML
  use_cache_TS: true
  bloomberg_subscription_config_path: "utils/LiveSubscriptionManager/config_bloomberg_subscription.yaml"

####trade params###########################

  trade_export_sheet: Trades
  trade_export_cell: A3            # Cella in cui esportare i trades_df
  number_of_trades_to_show: 200     # Numero di trades_df da mostrare
  min_ctv_to_show_trades: 2         # Controvalore minimo per mostrare i trades_df
  trade_min_export_interval: 0.1      # Secondi per l'intervallo minimo di esportazione trades_df
  output_trade_columns: ["last_update", "price", "quantity", "ctv", "side", "own_trade"]
  book_storage_size: 3  #by doing book storage time_lag_in_seconds = size * (tasks-> update_HF -> frequency)

#####price output_NAV###########################
  output_prices_cell: "A1"
  output_prices_sheet: PriceContainer

####pricing params###########################

  pricing:
    driver:
      forecast_aggregation: ewma_outlier
      trimmed_mean:
        perc_outlier: 0.3
      ewma_outlier:
        halflife: 10
        outlier_std: 3

    cluster:
      forecast_aggregation: ewma_outlier
      trimmed_mean:
        perc_outlier: 0.3
      ewma_outlier:
        halflife: 10
        outlier_std: 3

    nav:
      forecast_aggregation: ewma_outlier
      trimmed_mean:
        perc_outlier: 0.3
      ewma_outlier:
        halflife: 10
        outlier_std: 3

  tasks:
    update_HF:
      activate: true
      frequency: 1
    update_LF:
      activate: false
      frequency: 60
    data_storing:
      activate: false
      frequency: 300
    trade:
      activate: true
      synchronous: false
      frequency: 1
    dynamic_params:
      activate: true
      dynamic_config_path: C:\AFMachineLearning\Projects\Trading\MarketMonitorFI\configFolder\dynamic_config.yaml
      frequency: 1


  DB connection:
    Database Type : Oracle
    Username : AF_PCF
    Password : AAAbbb2022!!!
    Host : dcdwboh-cli.sg.gbs.pro
    Port : 1521
    Service Name : OTH_ORABOH.bsella.it


market_data_distributor:
  activate: true
  book_params:
    fields: ["MID"]
    mid_key: ["MID"]
    max_var_threshold: 0.05 #max_perc_ret

  bloomberg_params:
    options:
      interval: 0

trade_distributor:
  activate: true
  path: "C:\\Users\\gbs09316\\Documents\\marketTradeFolder"


excel_data_distributor:
  activate: false
  excel_params:
    path: "Price_Engine.xlsx"
    sheet_names: ["HF_Prices"]
    book_reading_frequency: 1

gui:
  gui_type: ThreadGUIExcel
  new_instance: false               # Valori booleani in minuscolo
  visible: true
  add_book: false
  thread_queue_size: 5
  path: "Price_Engine.xlsx"

logging:
  log_level: INFO
  log_level_console: WARNING
  log_name: FI_market_monitor.log
