strategy_name: FIAnalysis

market_monitor:

  #strategy_name: MarketMonitorDummy

####trade params###########################

  trade_export_cell: A9           # Cella in cui esportare i trades
  trade_export_sheet: Pricing

  trade_manager:
    show_my_trades: False
    min_ctv_to_show_trades: 15000
    number_of_trades_to_show: 200     # Numero di trades da mostrare
    trade_min_export_interval: 0.1      # Secondi per l'intervallo minimo di esportazione trades
    output_trades_columns: ["isin", "market", "currency", "last_update", "price", "quantity", "ctv", "side", "own_trade"]
  book_storage_size: 3  #by doing book storage time_lag_in_seconds = size * (tasks-> update_HF -> frequency)

#####price output_NAV###########################
  output_prices_cell: "A1"
  output_prices_sheet: PriceContainer

  tasks:
    update_HF:
      activate: true
      frequency: 1

    update_LF:
      activate: false
      frequency: 60
    data_storing:
      activate: false
      frequency: 300
    trade:
      activate: true
      synchronous: false
      frequency: 1
    dynamic_params:
      activate: false
      dynamic_config_path: C:\AFMachineLearning\Projects\Trading\MarketMonitorFI\configFolder\dynamic_config.yaml
      frequency: 1

  sql_db_fi_file: 'C:\AFMachineLearning\Projects\Trading\FxdIncomeEtfAnalysis\FxdIncomeEtfDB.db'



market_data_distributor:
  activate: true
  book_params:
    fields: ["MID"]
    mid_key: ["MID"]
    max_var_threshold: 0.05 #max_perc_ret

  bloomberg_params:
    options:
      interval: 0

redis_data_distributor:
  activate: true
  redis_params:
    redis_host: 'localhost'
    redis_port: 6379
    redis_db: 0

trade_distributor:
  activate: true
  path: C:\\Program Files\\Banca Sella Holding\\Market Trades Viewer DB
  db_name: markettrades.db



gui:
  TradeGUI:
    gui_type: TradeThreadGUITkinter
  Excel:
    gui_type: ThreadGUIExcel
    new_instance: false               # Valori booleani in minuscolo
    visible: true
    add_book: false
    thread_queue_size: 5
    path: V:\ETF\Risk Management\Trade_Container.xlsm

logging:
  log_level: INFO
  log_level_console: WARNING
  log_name: FIAnalysis.log

oracle_connection:
  environment: PROD
  user: AF_QUANTLIB
  tns_name: ORABOH
  password: b18289f251b94f0e1a819df7c7a0fb2e9fabf457ba67b5bbf584478db8c8c17e
  schema: AF_DATAMART_DBA
