strategy_name: StrategyDummy

market_monitor:
  tasks:
    update_HF:
      activate: true
      frequency: 0.01
    update_LF:
      activate: false
      frequency: 60
    data_storing:
      activate: false
      frequency: 600
    trade:
      activate: true
      synchronous: false
      frequency: 1
    dynamic_params:
      activate: false
      dynamic_config_path: "configFolder/dynamicEquityQuoting.yaml"
      frequency: 1

excel_data_distributor:
  activate: false

logging:
  log_level: DEBUG
  log_level_console: WARNING
  log_name: Dummy.log


market_data_distributor:
  activate: true
  book_params:
    fields: ["BID","ASK"]
    mid_key: ["BID","ASK"]
    max_var_threshold:   #max_perc_ret
  bloomberg_params:
    options:
      interval: 0
      delayed: False

redis_data_distributor:
  activate: false
  redis_params:
    redis_host: 'localhost'
    redis_port: 6379
    redis_db: 0

trade_distributor:
  activate: false
  path: "C:\\Users\\gbs09316\\Documents\\marketTradeFolder"

gui:
  gui_type: GUIDummy
  heartbeat:
    heartbeat_name: "HeartBeatDuma"
    heartbeat_interval: 1
    macro_name_heartbeat: "SendPublishingSignal"
    macro_name_stop: "sendOffSignal"

  new_instance: false
  visible: true
  add_book: false
  thread_queue_size: 5
  path: "V:\\EquityETF\\PriceEngine.xlsm"
