strategy_name: NavChecking

market_monitor:

  instruments: [
                "IE00BPVLQD13",
                "LU0514695690",
                "IE00B95PGT31",
                "LU1900067940",
                "IE00B4L5YX21",
                "IE00B02KXH56",
                "IE00B53QDK08",
                "IE00BFXR5T61",
                "LU0136240974",
                "LU1841731745",
                "LU1781541252",
                "FR0010245514",
                "LU0950671825",
                "LU1900068914",
                "LU2456436083",
                "IE00B02KXK85",
                "LU2314312849",
                "LU0292109856",
                "LU1953188833",
                "LU0274209740",
                "LU1931974775",
                "IE00BHZRR147"]


  
  tasks:
    update_HF:
      activate: true
      frequency: 3
    update_LF:
      activate: true
      frequency: 60
    data_storing:
      activate: true
      frequency: 600
    trade:
      activate: true
      synchronous: false
      frequency: 1
    dynamic_params:
      activate: true
      dynamic_config_path: "configFolder/isin_check.yaml"
      frequency: 1

  db_name:  DataStorage/data_storage.db

  DB connection:
    Database Type : Oracle
    Username : AF_PCF
    Password : AAAbbb2022!!!
    Host : dcdwboh-cli.sg.gbs.pro
    Port : 1521
    Service Name : OTH_ORABOH.bsella.it


market_data_distributor:
  activate: true
  book_params:
    fields: ["MID"]
    mid_key: ["MID"]
    max_var_threshold:  #max_perc_ret

  bloomberg_params:
    options:
      interval: 0
      delayed:

trade_distributor:
  activate: false

excel_data_distributor:
  activate: false
  excel_params:
    path: "liveNavDashboard.xlsx"
    sheet_names: ["Sheet3"]
    book_reading_frequency: 1

#gui:
#  gui_type: ThreadGUITkinter
#  thread_queue_size: 5
#  update_interval: 120

gui:
  gui_type: ThreadGUIExcel
  new_instance: false
  visible: true
  add_book: false
  thread_queue_size: 5
  path: "liveNavDashboard.xlsx"

logging:
  log_level: INFO
  log_level_console: WARNING
  log_name: NavChecking.log


