load_strategy_info:
      package_path: C:\AFMachineLearning\Libraries\MarketMonitor\user_strategy\corporate
      module_name: CBTradeAnalysis
      class_name: CBTradeAnalysis

timescale_connection:
  host: timescaledb.af.pro
  database: aidb
  port: 5432
  user: aivwr
  password: 63903918ce20c5d534c3eb551202d4ea


market_monitor:

  trade_manager:
    show_my_trades: True
    output_trade_columns: ["isin","last_update","price","quantity","ctv","side","own_trade","spread_pl"]


  tasks:
    update_HF:
      activate: true
      frequency: 2
    update_LF:
      activate: true
      frequency: 60
    trade:
      activate: true
      synchronous: false
      frequency: 1
    dynamic_params:
      activate: false
      dynamic_config_path: "configFolder/dynamicEquityQuoting.yaml"
      frequency: 1


bloomberg_data_distributor:
  activate: false

kafka_data_distributor:
  activate: true
  kafka_params:
    bootstrap_servers: "aftstserver51.af.tst:9092,aftstserver52.af.tst:9092,aftstserver53.af.tst:9092"
    schema_registry_url: "http://aftstserver51.af.tst:8081"
    start_mode: "latest"  # oppure "earliest"

trade_distributor:
  activate: true
  path: "C:\\Program Files\\Banca Sella Holding\\Market Trades Viewer DB\\markettrades.db"

redis_data_distributor:
  activate: false
  redis_params:
    redis_host: 'localhost'
    redis_port: 6379
    redis_db: 0

logging:
  log_level: INFO
  log_level_console: WARNING
  log_name: LiveAnalysis.log


