load_strategy_info:
      package_path: C:\AFMachineLearning\Libraries\MarketMonitor\user_strategy\equity\LiveAnalysis
      module_name: EtfEquityLiveAnalysis
      class_name: EtfEquityLiveAnalysis


market_monitor:

  path_db: etc/input/EtfEquityDB.db
  bloomberg_subscription_config_path: C:\AFMachineLearning\Libraries\MarketMonitor\etc\config\bbg_subscription\config_bloomberg_subscription.yaml
  price_source: "bloomberg"
  min_ctv_trades_excel: 20000
  trade_manager:
    show_my_trades: True
    output_trade_columns: ["ticker","last_update","price","quantity","ctv","side","own_trade","spread_pl"]
    min_ctv_to_show_trades: 5000
    number_of_trades_to_show: 200


  tasks:
    update_HF:
      activate: true
      frequency: 2
    update_LF:
      activate: true
      frequency: 60
    trade:
      activate: true
      synchronous: true
      frequency: 1
    dynamic_params:
      activate: false
      dynamic_config_path: "configFolder/dynamicEquityQuoting.yaml"
      frequency: 1


bloomberg_data_distributor:
  activate: true
  interval: 1


kafka_data_distributor:
  activate: true
  kafka_params:
    bootstrap_servers: "aftstserver51.af.tst:9092,aftstserver52.af.tst:9092,aftstserver53.af.tst:9092"
    schema_registry_url: "http://aftstserver51.af.tst:8081"
    start_mode: "latest"  # oppure "earliest"


trade_distributor:
  activate: true
#  path: C:\AFMachineLearning\Libraries\MarketMonitor\etc\marketrades.db
  path: "C:\\Users\\gbs09316\\Documents\\marketTradeFolder\\markettrades.db"

redis_data_distributor:
  activate: true
  redis_params:
    redis_host: 'localhost'
    redis_port: 6379
    redis_db: 0

logging:
  log_level: INFO
  log_level_console: WARNING
  log_name: LiveAnalysis.log


