strategy_name: RedisPublisherStrategy

market_monitor:

  instruments: [
          "LU0514695690",
          "LU1900067940",
          "LU1841731745",
          "LU1900068914",
          "LU2456436083",
          "IE00B02KXK85",
          "LU2314312849",
          "LU0292109856",
          "LU1953188833",
          "IE00BHZRR147",
          "IE00B44T3H88",
          "IE00BDGN9Z19",
          "IE00B910VR50",
          "LU1291098827",
          "IE00B53QG562",
          "IE00B53L3W79",
          "LU0274211217",
          "LU1931974429",
          "LU0380865021",
          "FR0007054358",
          "LU1681047236",
          "LU0147308422",
          "IE00BCLWRF22",
          "LU0136234068",
          "IE00BYXZ2585",
          "LU0846194776",
          "LU0950668870",
          "IE0008471009",
          "LU0950674175",
          "LU1291097779",
          "IE00BTJRMP35",
          "LU0480132876",
          "LU1781541849",
          "IE00BLRPN388",
          "LU2573967036",
          "IE00B5L8K969",
          "LU2573966905",
          "IE00B469F816",
          "IE00B4L5YC18",
          "IE00BKM4GZ66",
          "IE00BHZPJ239",
          "FR0010429068",
          "LU2109787049",
          "IE00B466KX20",
          "LU1681044480",
          "IE00B0M63177",
          "LU1900068161",
          "LU1681045370",
          "FR0010261198",
          "IE00BKWQ0Q14",
          "LU1931974262",
          "IE00B945VV12",
          "LU0328475792",
          "LU1681042609",
          "LU0908500753",
          "IE00BKLTRN76",
          "IE0001JH5CB4",
          "LU0446734104",
          "LU1600334798",
          "IE00BKSBGT50",
          "IE00BK5BQX27",
          "IE00BHZPJ783",
          "LU0322253732",
          "LU1437015735",
          "LU0274209237",
          "IE00BJQRDL90",
          "IE00B4K48X80",
          "LU1291099718",
          "IE00BPVLQD13",
          "IE00B95PGT31",
          "IE00B4L5YX21",
          "IE00B02KXH56",
          "IE00B53QDK08",
          "IE00BFXR5T61",
          "LU0136240974",
          "LU1781541252",
          "FR0010245514",
          "LU0950671825",
          "LU0274209740",
          "LU1931974775",
          "IE00BFMXYX26",
          "IE000QDFFK00",
          "IE00B53SZB19",
          "LU1681038243",
          "IE00BFZXGZ54",
          "IE0032077012",
          "IE00BMFKG444",
          "LU1829221024",
          "LU1681038672",
          "IE00B3CNHJ55",
          "IE00BJ38QD84",
          "IE00BJZ2DD79",
          "IE00BK5BQW10",
          "IE00BJ0KDR00",
          "IE00B5BMR087",
          "IE00B52SFT06",
          "IE00BHZPJ908",
          "IE00BFMXXD54",
          "IE0031442068",
          "LU0496786574",
          "LU0136234654",
          "IE00B77D4428",
          "FR0011550185",
          "LU1681048804",
          "IE00B3XXRP09",
          "LU1781540957",
          "IE00BJZ2DC62",
          "IE00BFXR5Q31",
          "IE00B7K93397",
          "IE000Z9SJA06",
          "IE00BD4TXS21",
          "IE00B6YX5C33",
          "IE00B3ZW0K18",
          "IE000G2LIHG9",
          "LU0959211326",
          "IE00BD4TYG73",
          "IE00BM67HW99",
          "LU0959211243",
          "LU1681049109",
          "IE000TSML5I8",
          "IE00BYYW2V44",
          "IE00BG04M077",
          "FR0010315770",
          "IE00BFNM3J75",
          "LU1781541179",
          "IE00BJ0KDQ92",
          "IE00B4L5Y983",
          "FR0014003IY1",
          "IE00BK5BQV03",
          "LU1681043599",
          "IE00B60SX394",
          "IE00BHZPJ569",
          "IE00BKX55T58",
          "IE00BFY0GT14",
          "LU0340285161",
          "IE00BCHWNQ94",
          "IE00B0M62Q58"]

  tasks:
    update_HF:
      activate: true
      frequency: 0.1
    update_LF:
      activate: false
      frequency: 60
    data_storing:
      activate: false
      frequency: 600
    trade:
      activate: false
      synchronous: false
      frequency: 1

gui:
  gui_type: GUIRedis

logging:
  log_level: DEBUG
  log_level_console: WARNING
  log_name: RedisPub.log


